package microvm

import (
	"errors"
	"fmt"

	"github.com/spf13/cobra"
	"go.uber.org/zap"

	"github.com/liquidmetal-dev/fl/pkg/app"
)

const (
	defaultNamespace   = "default"
	defaultVCPU        = 2
	defaultMemoryMb    = 2048
	defaultKernelImage = "ghcr.io/liquidmetal-dev/firecracker-kernel:6.1"
	defaultKernelFile  = "vmlinux"
	defaultRootImage   = "ghcr.io/liquidmetal-dev/ubuntu:24.04"
)

func newCreateCommand() *cobra.Command {
	createInput := &app.CreateInput{}

	cmd := &cobra.Command{
		Use:   "create",
		Short: "create a new microvm",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if createInput.Name != "" && createInput.NameAutogenerate {
				return errors.New("only one of --name or --name-autogenerate can be specified")
			}

			if createInput.Name == "" && !createInput.NameAutogenerate {
				return errors.New("you must supply one of --name or --name-autogenerate")
			}

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			a := app.New(zap.S().With("action", "create"))

			if err := a.Create(cmd.Context(), createInput); err != nil {
				return fmt.Errorf("creating microvm: %s", err)
			}

			return nil
		},
	}

	cmd.MarkFlagRequired("host")

	cmd.Flags().StringVar(&createInput.Host, "host", "", "the flintlock host to create the microvm on")
	cmd.Flags().StringVar(&createInput.Name, "name", "", "the name of the microvm, cannot be specified if using name-autogenerate")
	cmd.Flags().BoolVar(&createInput.NameAutogenerate, "name-autogenerate", false, "if true a name is autogenerated for the microvm")
	cmd.Flags().StringVar(&createInput.Namespace, "namespace", defaultNamespace, "the namespace for the microvm")
	cmd.Flags().IntVar(&createInput.VCPU, "vcpu", defaultVCPU, "the number of vcpus")
	cmd.Flags().IntVar(&createInput.MemoryInMb, "memory", defaultMemoryMb, "the memory in mb")
	cmd.Flags().StringVar(&createInput.KernelImage, "kernel-image", defaultKernelImage, "the image to use for the kernel")
	cmd.Flags().BoolVar(&createInput.KernelAddNetConf, "add-netconf", true, "automatically add network configuration to the kernel cmd line")
	cmd.Flags().StringVar(&createInput.KernelFileName, "kernel-filename", defaultKernelFile, "name of the kernel file in the image")
	cmd.Flags().StringVar(&createInput.RootImage, "root-image", defaultRootImage, "the image to use for the root volume")
	cmd.Flags().StringVar(&createInput.InitrdImage, "initrd-image", "", "the image to use for the initial ramdisk")
	cmd.Flags().StringVar(&createInput.InitrdFilename, "initrd-filename", "", "name of the file in the image to use for the initial ramdisk")
	cmd.Flags().StringSliceVar(&createInput.NetworkInterfaces, "network-interface", []string{}, "specify the network interfaces to attach. In the following format: name:type:[macaddress]:[ipaddress]")
	cmd.Flags().StringSliceVar(&createInput.MetadataFromFile, "metadata-from-file", []string{}, "specify metadata to be available to your microvm. In the following format key=pathtofile")
	cmd.Flags().StringVar(&createInput.Metadata.Hostname, "metadata-hostname", "", "the hostname of the the microvm")
	cmd.Flags().StringVar(&createInput.Metadata.SSHKeyFile, "metadata-ssh-key-file", "", "an ssh key to use")
	cmd.Flags().StringSliceVar(&createInput.Metadata.SshImportIds, "metadata-ssh-import-id", []string{}, "ssh keys to import. The keyserver can be specified by prepending either lp: for Launchpad or gh: for GitHub to the username.")
	cmd.Flags().BoolVar(&createInput.Metadata.ResolvdFix, "metadata-resolvd-fix", true, "include a systemd-resolvd fix for container root volumes")
	cmd.Flags().StringVar(&createInput.Metadata.Message, "metadata-final-message", "", "set the cloud-init final message")
	cmd.Flags().StringSliceVar(&createInput.AdditionalContainerVolumes, "container-volume", []string{}, "attach additional volumes using a container image, The following format: name=containerimage=mountpoint")
	cmd.Flags().StringVar(&createInput.AdditionalVirtioFSVolume, "virtiofs-volume", "", "attach an additional volume using virtiofs, use the following format: name=localpath=mountpoint")
	cmd.Flags().BoolVar(&createInput.AllowGuestAgent, "allow-guest-agent", false, "attach a vsock device so the in-guest guest-agent can communicate with the host")

	// TODO: additional command line args for kernel
	// TODO: add additional volumes

	return cmd
}
