version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - maintainer: Richard Case <richard@liquidmetal.dev>
    vendor: Liquid Metal Project
    homepage: https://liquidmetal.dev/
    file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - apk
      - deb
      - rpm
