version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - maintainer: Richard Case <richard@liquidmetal.dev>
    vendor: Liquid Metal Project
    homepage: https://liquidmetal.dev/
    formats:
      - apk
      - deb
      - rpm
